#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#


echo "pre-push hook: ${PWD}/$0..."
echo "we have lift-off..."
echo '   /\'
echo '  (  )'
echo '  (  )'
echo ' /|/\|\'
echo '/_||||_\'
echo '   ** '

