#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".


# this hook executes just prior to a commit
echo "pre-commit hook..."
echo ' /\_/\'
echo '((@v@))'
echo '():::()'
echo ' VV-VV'
echo "Friendly reminder:"
echo '  npm run lint'
echo '  npm run test'

